#!/bin/sh

#
# Author: Jose Luis Rivas <ghostbar at gmx.com>
# Filename: builder
# Date: October 30, 2008, 02:06.
#
# Copyright (c) 2008 Jose Luis Rivas <ghostbar at gmx.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

help="
This is a script helping git-bp-tools-extra with build
options.

Options:
-v/--version			Print version.
-h/--help			Print this help.
-b				Builds.
-l/--lintian			Only checks lintian


Last version downloadable from:
git://git.rivco.info/misc/git-buildpackage-extra-tools.git
"

version="
Helper script for building packages with git-bp-tools-extra
Version: 0.01
Copyright 2008 Jose Luis Rivas <ghostbar at gmx.com>
"

checkbadir() {
	if test ! -e ../b-a; then
		mkdir ../b-a
	fi
}

callpdebuild() {
	pdebuild --pbuilder cowbuilder --buildresult ../b-a --debsign-k CACAB118 --auto-debsign	--debbuildopts '-v${EXV} -I.git -i\.git ${EXOP}' -- --basepath ${BSPATH}
}

signpackages() {
	debsign -kcacab118 ../$(grep -m 1 ';' debian/changelog | sed 's/ .*//')_$(grep -m 1 ';' debian/changelog | sed 's/.*(//' | sed 's/).*//')_*.changes
}

checklintian() {
	lintian -i ../b-a/$(grep -m 1 ';' debian/changelog | sed 's/ .*//')_$(grep -m 1 ';' debian/changelog | sed 's/.*(//' | sed 's/).*//')_*.changes
	echo "There's $(lintian ../b-a/$(grep -m 1 ';' debian/changelog | sed 's/ .*//')_$(grep -m 1 ';' debian/changelog | sed 's/.*(//' | sed 's/).*//')_*.changes | wc -l) lintian warnings."
}

#main part of the script

while test -n "$1"; do
	case $1 in
	+(-v|--version)	
		echo "$version"; exit 0;;
	-b)	
		checkbadir
		callpdebuild
		signpackages
		checklintian
		exit 0;;
	+(-l|--lintian)
		checklintian > ../lintian; exit 0;;
	*)	
		echo "$help"; exit 0;;
	esac
done

if test -z $1; then
	echo "$help"; exit 0
fi
